# Generated by Django 4.2.3 on 2023-07-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Bus', 'Bus'), ('Semi', 'Semi')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/customer/images'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/vehicle/images')),
                ('type', models.CharField(blank=True, choices=[('2', '2 wheeler'), ('4', '4 wheeler'), ('6', '6 wheeler'), ('8', '8 wheeler'), ('12', '12 wheeler')], max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.vehiclecategory')),
            ],
        ),
    ]
