# Generated by Django 4.2.3 on 2023-07-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_vehiclecategory_alter_customer_image_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/store/images/customer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/store/images/vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Bus', 'Bus'), ('Semi', 'Semi'), ('Heavy', 'Heavy'), ('Machinery', 'Machinery')], max_length=100),
        ),
    ]
