# Generated by Django 4.2.3 on 2023-07-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_image_alter_vehicle_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecategory',
            name='image',
            field=models.ImageField(default='hello.jpg', upload_to='media/store/images/vehicle_category'),
            preserve_default=False,
        ),
    ]
