# Generated by Django 4.2.3 on 2023-07-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_vehiclecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='vehiclecategory',
            name='type',
            field=models.CharField(blank=True, choices=[('2', '2 wheeler'), ('4', '4 wheeler'), ('6', '6 wheeler'), ('8', '8 wheeler'), ('12', '12 wheeler')], max_length=2),
        ),
    ]
