# Generated by Django 4.2.3 on 2023-07-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_vehiclecategory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='store/images/vehicle_part')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store/images/customer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='h.jpg', upload_to='store/images/vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='image',
            field=models.ImageField(upload_to='store/images/vehicle_category'),
        ),
    ]
