# Generated by Django 4.2.3 on 2023-07-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='vehicle_part_speciality',
            field=models.CharField(choices=[('wheel', 'wheel'), ('engine', 'engine'), ('body', 'body'), ('chassis', 'chassis'), ('electricity', 'electricity'), ('other', 'other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='vehicle_speciality',
            field=models.CharField(choices=[('bike', 'bike'), ('car', 'car'), ('semi', 'semi'), ('heavy', 'heavy'), ('machinery', 'machinery')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(choices=[('bike', 'bike'), ('car', 'car'), ('bus', 'bus'), ('semi', 'semi'), ('heavy', 'heavy'), ('machinery', 'machinery')], max_length=100),
        ),
    ]
