# Generated by Django 4.2.3 on 2023-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_vehiclecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(choices=[('Bike', 'Bike'), ('car', 'car'), ('bus', 'bus'), ('semi', 'semi'), ('heavy', 'heavy'), ('machinery', 'machinery')], max_length=100),
        ),
    ]
