# Generated by Django 4.2.3 on 2023-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_vehiclecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='vehicle_part_speciality',
            field=models.CharField(choices=[('wheel', 'Wheel'), ('engine', 'Engine'), ('body', 'Body'), ('chassis', 'Chassis'), ('electricity', 'Electricity'), ('other', 'Other')], max_length=255),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='vehicle_speciality',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('semi', 'Semi'), ('heavy', 'Heavy'), ('machinery', 'Machinery')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='name',
            field=models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('bus', 'Bus'), ('semi', 'Semi'), ('heavy', 'Heavy'), ('machinery', 'Machinery')], max_length=100),
        ),
    ]
