# Generated by Django 4.2.3 on 2023-07-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRepairRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('location_coordinates', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('preferred_mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.mechanic')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRepairRequestVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='store/images/repair_request/videos')),
                ('repair_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='store.vehiclerepairrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRepairRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store/images/repair_request/images')),
                ('repair_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.vehiclerepairrequest')),
            ],
        ),
    ]
