# Generated by Django 4.2.3 on 2023-07-14 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_vehiclerepairrequestvideo_repair_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepairrequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclerepairrequest',
            name='vehicle_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.vehiclepart'),
        ),
    ]
