# Generated by Django 4.2.3 on 2023-10-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_vehiclerepairrequest_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('away', 'Away'), ('on the way', 'On the way'), ('on repair process', 'On repair process')], default='available', max_length=100),
        ),
        migrations.CreateModel(
            name='VehicleRepairProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.customer')),
                ('mechanic', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='store.mechanic')),
            ],
        ),
    ]
