# Generated by Django 4.2.3 on 2023-10-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_sparepartbillimage_vehiclerepair_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='woner_name_number',
            new_name='woner_number',
        ),
    ]
