# Generated by Django 4.2.3 on 2023-10-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_rename_woner_name_number_workshop_woner_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclerepairoverview',
            name='workshop_need',
        ),
        migrations.AddField(
            model_name='vehiclerepairoverview',
            name='workshop_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclerepairoverview',
            name='mechanic_charge',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehiclerepairoverview',
            name='needs_to_tow',
            field=models.BooleanField(default=False),
        ),
    ]
