# Generated by Django 4.2.3 on 2023-10-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_vehiclerepair_mechanic_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepairoverview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
