# Generated by Django 4.2.3 on 2023-10-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_vehiclerepairoverview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerepairoverview',
            name='estimated_time',
            field=models.TimeField(default='00:03:00'),
            preserve_default=False,
        ),
    ]
