# Generated by Django 4.2.3 on 2023-10-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_vehiclerepairoverview_estimated_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclerepairoverview',
            old_name='estimated_time',
            new_name='estimate_time',
        ),
    ]
